CUDA_VISIBLE_DEVICES=1 python main_test.py --mode test \
--dataset lapa \
--model enet \
--channels 3 \
--out_channels 11 \
--logdir ./kd/resume_s_model_enet \
--datapath ./LaPa/ \
--testlist lapa_test_30.txt \
--test_batch_size 1 \
--test_crop_height 512 --test_crop_width 512 \
--saveresult ./enet_59_41000-2/